In [6]:
import pandas as pd
import pyodbc 

conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=KTDBBIPRD;'
                      'Database=BIDEV;'
                      'Trusted_Connection=yes;')

weatherdf = pd.read_sql_query('SELECT * FROM stg.WeatherCurrentAndHistorical WHERE convert(date,CurrentTime) between \'2020-12-01\' and \'2021-04-01\'', conn)

In [8]:
weatherdf.head(10)

,Id,SiteNumber,ZipCode,City,State,Latitude,Longitude,TimeZone,TimeZoneOffset,CurrentTime,...,DewPoint,Uvi,Clouds,Visibility,WindSpeed,WindDegree,WindGust,ProcessedTime,Rain,Snow
0,29664855,1004,50703,WATERLOO,IA,42.546,-92.281,America/Chicago,-18000,2020-12-01 03:20:00,...,16.7,None,None,None,1.4,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
1,29664856,601,54403,WAUSAU,WI,45.034,-89.510,America/Chicago,-18000,2020-12-01 03:20:00,...,15.6,None,None,None,5.8,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
2,29664857,339,53807,CUBA CITY,WI,42.631,-90.383,America/Chicago,-18000,2020-12-01 03:20:00,...,18.8,None,None,None,5.1,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
3,29664858,207,52742,DE WITT,IA,41.834,-90.506,America/Chicago,-18000,2020-12-01 03:20:00,...,18.1,None,None,None,5.8,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
4,29664859,705,50670,SHELL ROCK,IA,42.687,-92.615,America/Chicago,-18000,2020-12-01 03:20:00,...,17.3,None,None,None,2.3,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
5,29664860,188,54403,WAUSAU,WI,45.034,-89.510,America/Chicago,-18000,2020-12-01 03:20:00,...,15.6,None,None,None,5.8,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
6,29664861,632,52730,CAMANCHE,IA,41.766,-90.333,America/Chicago,-18000,2020-12-01 03:20:00,...,18.8,None,None,None,5.9,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
7,29664862,723,50703,WATERLOO,IA,42.546,-92.281,America/Chicago,-18000,2020-12-01 03:20:00,...,16.7,None,None,None,1.4,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
8,29664863,1154,51201,SHELDON,IA,43.180,-95.861,America/Chicago,-18000,2020-12-01 03:20:00,...,18.8,None,None,None,9.9,None,0.0,2021-05-28 01:30:03.100,0.0,0.0
9,29664864,292,54311,GREEN BAY,WI,44.473,-87.902,America/Chicago,-18000,2020-12-01 03:20:00,...,19.2,None,None,None,11.9,None,0.0,2021-05-28 01:30:03.100,0.0,0.0

In [11]:
weatherdf.columns

Index(['Id', 'SiteNumber', 'ZipCode', 'City', 'State', 'Latitude', 'Longitude',
       'TimeZone', 'TimeZoneOffset', 'CurrentTime', 'SunriseTime',
       'SunsetTime', 'Temperature', 'FeelsLike', 'Pressure', 'Humidity',
       'DewPoint', 'Uvi', 'Clouds', 'Visibility', 'WindSpeed', 'WindDegree',
       'WindGust', 'ProcessedTime', 'Rain', 'Snow'],
      dtype='object')

In [42]:
weatherdf = weatherdf.filter(['Id','SiteNumber','ZipCode','City','State','Latitude','Longitude','CurrentTime','Temperature','FeelsLike','Rain','Snow'])

In [43]:
weatherdf.head()

,Id,SiteNumber,ZipCode,City,State,Latitude,Longitude,CurrentTime,Temperature,FeelsLike,Rain,Snow
0,29664855,1004,50703,WATERLOO,IA,42.546,-92.281,2020-12-01 03:20:00,22.1,22.1,0.0,0.0
1,29664856,601,54403,WAUSAU,WI,45.034,-89.510,2020-12-01 03:20:00,19.8,11.7,0.0,0.0
2,29664857,339,53807,CUBA CITY,WI,42.631,-90.383,2020-12-01 03:20:00,23.0,16.3,0.0,0.0
3,29664858,207,52742,DE WITT,IA,41.834,-90.506,2020-12-01 03:20:00,24.1,16.9,0.0,0.0
4,29664859,705,50670,SHELL ROCK,IA,42.687,-92.615,2020-12-01 03:20:00,21.2,21.2,0.0,0.0

In [44]:
groupbydf = weatherdf.groupby(['SiteNumber',weatherdf.CurrentTime.dt.date]).agg({"Temperature":'min',"Snow":'sum'})

In [45]:
groupbydf.head()

                        Temperature  Snow
SiteNumber CurrentTime
103        2020-12-01           0.0   0.0
           2020-12-02          15.3   0.0
           2020-12-03          23.6   0.0
           2020-12-04          23.3   0.0
           2020-12-05          21.5   0.0

In [46]:
groupbydf.columns

Index(['Temperature', 'Snow'], dtype='object')

In [47]:
groupbydf.index

MultiIndex([( 103, 2020-12-01),
            ( 103, 2020-12-02),
            ( 103, 2020-12-03),
            ( 103, 2020-12-04),
            ( 103, 2020-12-05),
            ( 103, 2020-12-06),
            ( 103, 2020-12-07),
            ( 103, 2020-12-08),
            ( 103, 2020-12-09),
            ( 103, 2020-12-10),
            ...
            (1531, 2021-03-23),
            (1531, 2021-03-24),
            (1531, 2021-03-25),
            (1531, 2021-03-26),
            (1531, 2021-03-27),
            (1531, 2021-03-28),
            (1531, 2021-03-29),
            (1531, 2021-03-30),
            (1531, 2021-03-31),
            (1531, 2021-04-01)],
           names=['SiteNumber', 'CurrentTime'], length=100162)

In [48]:
#convert mm to inches
groupbydf.Snow = groupbydf.Snow/25.4

In [49]:
#all entries for site 103
groupbydf.loc[103]

             Temperature  Snow
CurrentTime
2020-12-01           0.0   0.0
2020-12-02          15.3   0.0
2020-12-03          23.6   0.0
2020-12-04          23.3   0.0
2020-12-05          21.5   0.0
...                  ...   ...
2021-03-28          32.8   0.0
2021-03-29          39.4   0.0
2021-03-30          24.6   0.0
2021-03-31          19.0   0.0
2021-04-01          17.5   0.0

[122 rows x 2 columns]

In [65]:
#the most snowfall among all sites on Dec 1, 2020
groupbydf.loc[(slice(None),'2020-12-01'),'Snow'].max()

KeyError: '2020-12-01'